[package]
name = "fvm-workbench"
description = "Standalone Filecoin virtual machine for development, testing, and debugging"
version = "0.1.0"
license = "MIT OR Apache-2.0"
authors = ["@anorth"]
edition = "2021"

[dependencies]
fvm = { version = "3.0.0-alpha.11",  default-features = false }
fvm_shared = { version = "3.0.0-alpha.12" }
fvm_ipld_hamt = { version = "0.6.1" }
fvm_ipld_amt = { version = "0.5.0" }
fvm_ipld_car = { version = "0.6.0" }
fvm_ipld_blockstore = { version = "0.1.1" }
fvm_ipld_encoding = { version = "0.3.0" }

#anyhow = "1.0.47"
#cid = { version = "0.8.5", default-features = false }
#futures = "0.3.19"
#multihash = { version = "0.16.1", default-features = false }
#num-traits = "0.2"
#lazy_static = "1.4.0"
#libsecp256k1 = "0.7.0"
#rand = "0.8.5"
#rand_chacha = "0.3"
#serde = { version = "1.0", features = ["derive"] }
#serde_tuple = "0.5"
#serde_repr = "0.1"
thiserror = "1.0.30"

#wasmtime = {version = "1.0.2", default-features = false, features = ["cranelift", "parallel-compilation"]}

[patch.crates-io]
# Temporary solution to funty@1.2.0 being yanked.
# tracking issue: https://github.com/bitvecto-rs/funty/issues/7
funty = { git = "https://github.com/bitvecto-rs/funty/", rev = "7ef0d890fbcd8b3def1635ac1a877fc298488446" }