[workspace]
members = [
    "api",
    "builtin",
    "vm",
]

[package]
name = "fvm-workbench"
description = "Standalone Filecoin virtual machine for development, testing, and debugging"
version = "0.1.0"
license = "MIT OR Apache-2.0"
authors = ["@anorth"]
edition = "2021"

[patch.crates-io]
# Temporary solution to funty@1.2.0 being yanked.
# tracking issue: https://github.com/bitvecto-rs/funty/issues/7
funty = { git = "https://github.com/bitvecto-rs/funty/", rev = "7ef0d890fbcd8b3def1635ac1a877fc298488446" }